---
title: "Graphs"
author: "Riya Mehta"
date: "2023-11-08"
output: html_document
---

```{r}
library(plotly)
library(htmlwidgets)
library(webshot)
library(dplyr)
library(ggmap)
library(ggplot2)
```


```{r}
#read in csv files
missing_data <- read.csv("missing.csv")
state_crime <- read.csv("state_crime.csv")
substrate_data <- read.csv("SubstateRegionData161718.csv")

#create a dataframe to map state abbreviations to full names
state_mapping <- data.frame(
  abb = c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"),
  State = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "District of Columbia")
)

#merge missing_data with state_mapping based on state abbreviations
missing_data <- missing_data %>%
  left_join(state_mapping, by = c("State" = "abb"))

#rename columns
missing_data <- missing_data %>%
  rename(State_Abb = State) %>%
  rename(State = State.y)

#merge state_crime with state_mapping based on state names
state_crime <- state_crime %>%
  left_join(state_mapping, by = c("State" = "State"))

#rename column
state_crime <- state_crime %>%
  rename(State_Abb = abb)

#convert DLC (Date of Last Contact) to month, date, and year columns
missing_data$DLC <- as.character(missing_data$DLC)
split_date <- strsplit(missing_data$DLC, "/")

missing_data$Missing_Month <- sapply(split_date, function(x) x[1])
missing_data$Missing_Date <- sapply(split_date, function(x) x[2])
missing_data$Missing_Year <- sapply(split_date, function(x) x[3])

#convert columns to numeric
missing_data$Missing_Month <- as.numeric(missing_data$Missing_Month)
missing_data$Missing_Date <- as.numeric(missing_data$Missing_Date)
missing_data$Missing_Year <- as.numeric(missing_data$Missing_Year)

#these data were written out as new CSV files and are read in next
```


```{r}
missing_final <- read.csv("missing_data_cleaned.csv")
substrate_final <- read.csv("substrate_data_cleaned.csv")
state_crime_final <- read.csv("state_crime_cleaned.csv")
```


```{r}
#create dataframe with counts for each state
missing_counts <- table(missing_final$State)

#convert into dataframe with state and count of missing people
missing_counts_tab <- data.frame(State = names(missing_counts), Count = as.numeric(missing_counts))

#create a dataframe to map state abbreviations to full names
state_mapping <- data.frame(
  State_Abb = c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC"),
  State = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "District of Columbia")
)

#merge based on state names
missing_counts_tab <- missing_counts_tab %>%
  left_join(state_mapping, by = c("State" = "State"))
```


```{r}
#define color palette
color_palette <- colorRampPalette(c("white", "#720026"))(100)
outline_color <- "black"
title_text <- "State-wise Distribution of Missing Persons"

#create choropleth map
map_plot <- plot_ly(data = missing_counts_tab, type = 'choropleth', locations = ~State_Abb, locationmode = "USA-states", z = ~Count, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "Count of Missing People") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE,
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "dist_missing_persons.html")
#cat("<a href='dist_missing_persons.html' download>Download Interactive Map (HTML)</a>")
```


```{r}
#merge missing_counts_tab with substrate_final, selecting state and AMIYR
mental_illness_data <- missing_counts_tab %>%
  left_join(substrate_final %>% select(State, AMIYR), by = "State")

#group by state and calculate average AMIYR
averaged_mental_illness <- missing_counts_tab %>%
  left_join(substrate_final %>% select(State, AMIYR)) %>%
  group_by(State) %>%
  summarize(
    Average_AMIYR = mean(AMIYR, na.rm = TRUE),
    Count = first(Count),
    Abbreviation = first(State_Abb)
  )

color_palette <- colorRampPalette(c("white", "#720026"))(100)
outline_color <- "#720026"
```

```{r}
#insert your own Google Maps API key for geocoding
register_google(key = "")

#extract unique locations (City, State) from original dataset
city_names <- unique(missing_final[, c("City", "State")])

city_latitudes <- numeric()
city_longitudes <- numeric()

#loop through unique locations and geocode using API key
for (i in 1:nrow(city_names)) {
  loc <- city_names[i, ]
  loc_to_geocode <- paste(loc$City, loc$State, sep = ", ")
  result <- geocode(loc_to_geocode)
  city_latitudes[i] <- result$lat
  city_longitudes[i] <- result$lon
}

#add  latitudes and longitudes to the city_names
city_names$Lat <- city_latitudes
city_names$Lon <- city_longitudes
```

```{r}
#grouping missing_final data by city and state, summarizing counts
missing_counts_cities <- missing_final %>%
  group_by(City, State, State_Abb) %>%
  summarize(Count = n()) %>%
  ungroup()

#merge city_names with missing_counts_cities using city and state columns
unique_loc_with_counts <- left_join(city_names, missing_counts_cities, by = c("City", "State"))

#replace NA values in count column with 0
unique_loc_with_counts[is.na(city_names$Count), "Count"] <- 0
```
```{r}
#merge unique location data with missing persons counts per city and state
city_missing_map <- merge(unique_loc_with_counts, missing_counts_tab, by.x = "State", by.y = "State_Abb", all.x = TRUE)
title_text <- "Visualization of Missing Persons by City and State"

#create scattergeo map with markers representing cities and states
map <- plot_ly(data = city_missing_map, 
               lat = ~Lat, 
               lon = ~Lon, 
               marker = list(size = 6, opacity = 0.3, color = "#720026"), 
               type = 'scattergeo', 
               mode = 'markers', 
               text = ~paste("City: ", City, "<br>State: ", State, "<br>Count (City): ", Count.x, "<br>Count (State): ", Count.y),
               hoverinfo = 'text')

map <- map %>%
  layout(geo = list(scope = 'usa'))

map <- map %>%
  layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    showlegend = FALSE,
    paper_bgcolor = "white", 
    margin = list(t = 120),
    legend = list(title = "Legend Title") 
  )

map

#uncomment the following lines to download plot as html
#saveWidget(map, file = "dist_missing_persons_city.html")
#cat("<a href='dist_missing_persons_city.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
#plot not used in final presentation
#filter top 10 states by population in 2019
top_pop_2019 <- state_crime_final %>%
  filter(Year >= 1960 & Year <= 2019) %>%
  filter(Year == 2019) %>%
  arrange(desc(Data.Population)) %>%
  slice(2:11) %>%
  select(State)

#filter original dataset to have only top 10 states
top_pop_states_data <- state_crime_final %>%
  filter(State %in% top_pop_2019$State)

#create line plot
plot <- ggplot(top_pop_states_data, aes(x = Year, y = Data.Population, color = State)) +
  geom_line() +
  labs(
    x = "Year",
    y = "Population",
    title = "Change in Population Over Time (Top 10 States in 2019)"
  )

interactive_plot <- ggplotly(plot)

title_text <- "Change in Population Over Time (Top 10 States in 2019)"

interactive_plot <- interactive_plot %>%
  layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    xaxis = list(title = "Year"),
    yaxis = list(title = "Population"),
    showlegend = TRUE,
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

interactive_plot
```

```{r}
#filter all data for year 2018
missing_2018 <- missing_final %>% filter(Missing_Year == 2018)
state_crime_2018 <- state_crime_final %>% filter(Year == 2018)
missing_count_2018 <- missing_2018 %>% count(State)
state_crime_2018 <- state_crime_2018 %>% filter(!is.na(Data.Population))
```

```{r}
#average 2016-2018 populations
#count number of missing persons in each state for each year
missing_count_per_state_year <- missing_final %>%
  count(State, Missing_Year)

#jin missing persons count with state crime data, calculate proportion per 100,000 population
proportion_data <- missing_count_per_state_year %>%
  left_join(state_crime_final, by = c("State" = "State", "Missing_Year" = "Year")) %>%
  mutate(Proportion = n * 100000 / Data.Population) %>%
  filter(Missing_Year >= 2016 & Missing_Year <= 2018)

#calculate average proportion of missing persons per state
proportion_data <- proportion_data %>%
  group_by(State) %>%
  summarize(Avg_Proportion_Missing_Pop = mean(Proportion))

#join mental illness data with proportion data
averaged_data <- averaged_mental_illness %>%
  left_join(proportion_data, by = "State")

#calculate average ILLMON (Illicit Drug Use) per state
averaged_illmon <- substrate_final %>%
  group_by(State) %>%
  summarize(Average_ILLMON = mean(IEMMON, na.rm = TRUE))

#join average ILLMON data with overall averaged data
averaged_data <- averaged_data %>%
  left_join(averaged_illmon, by = "State")

#calculate average TXREC3 (mental health metric) per state
averaged_txrec3 <- substrate_final %>%
  group_by(State) %>%
  summarize(Average_TXREC3 = mean(TXREC3, na.rm = TRUE))

#join average TXREC3 data with overall averaged data
averaged_data <- averaged_data %>%
  left_join(averaged_txrec3, by = "State")
```

```{r}
# Load GeoJSON data
geojson <- jsonlite::read_json("GeoJSON.json")
title_text <- "Missing Persons per 100,000 State Population"

#create choropleth
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Avg_Proportion_Missing_Pop, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE,
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "dist_missing_persons_100k_alaska.html")
#cat("<a href='dist_missing_persons_100k_alaska.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
#filter out Alaska from the averaged_data
averaged_data_filtered <- averaged_data %>%
  filter(State != "Alaska")

title_text <- "Missing Persons per 100,000 State Population (Excluding Alaska)"

#create choropleth map
map_plot_filtered <- plot_ly(data = averaged_data_filtered, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Avg_Proportion_Missing_Pop, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE, 
      landcolor = "white", 
      showframe = FALSE, 
      subunitcolor = outline_color 
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot_filtered

#uncomment the following lines to download plot as html
#saveWidget(map_plot_filtered, file = "dist_missing_persons_100k.html")
#cat("<a href='dist_missing_persons_100k.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
title_text <- "State-wise Distribution of Average Illicit Drug Use (ILLOM)"

#create choropleth map for average illicit drug use
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Average_ILLMON, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "Average ILLMON") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE,
      subunitcolor = outline_color 
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120),
    legend = list(title = "Legend Title") 
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "dist_drug_alaska.html")
#cat("<a href='dist_drug_alaska.html' download>Download Interactive Map (HTML)</a>")
```
```{r}
#calculate ratio of average illicit drug use to missing persons
averaged_data$Drug_Missing_Ratio <- averaged_data$Average_ILLMON * averaged_data$Avg_Proportion_Missing_Pop

#filter out Alaska
averaged_data_filtered <- averaged_data %>%
  filter(c(State != "Alaska"), (State != "District of Columbia"))

color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Average Illicit Drug Use by Missing Persons Ratio (Excluding Alaska)"

#create choropleth map for ratio
map_plot <- plot_ly(data = averaged_data_filtered, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Drug_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average AMIYR: ", Average_AMIYR), colors = color_palette) %>%
  colorbar(title = "Ratio") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE, 
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "drug_ratio.html")
#cat("<a href='drug_ratio.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
#calculate ratio of average illicit drug use to missing persons
averaged_data$Drug_Missing_Ratio <- averaged_data$Average_ILLMON * averaged_data$Avg_Proportion_Missing_Pop

#filter out Alaska
averaged_data_filtered <- averaged_data %>%
  filter(c(State != "Alaska"), (State != "District of Columbia"))

color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Average Illicit Drug Use by Missing Persons Ratio"

#create choropleth map for ratio
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Drug_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average ILLMON: ", Average_ILLMON), colors = color_palette) %>%
  colorbar(title = "") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE, 
      showland = TRUE, 
      landcolor = "white", 
      showframe = FALSE, 
      subunitcolor = outline_color 
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "drug_ratio_alaska.html")
#cat("<a href='drug_ratio_alaska.html' download>Download Interactive Map (HTML)</a>")
```
```{r}
color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Average Illicit Drug Use by Missing Persons Ratio (Excluding Alaska)"

#create choropleth map for ratio excluding Alaska
map_plot <- plot_ly(data = averaged_data_filtered, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Drug_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average ILLMON: ", Average_ILLMON), colors = color_palette) %>%
  colorbar(title = "") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE, 
      landcolor = "white", 
      showframe = FALSE, 
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title") 
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "drug_ratio.html")
#cat("<a href='drug_ratio.html' download>Download Interactive Map (HTML)</a>")
```


```{r}
title_text <- "State-wise Distribution of Average Any Mental Illness (AMIYR) Score"

#create choropleth map for average AMIYR score
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Average_AMIYR, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "Average AMIYR") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE, 
      showland = TRUE, 
      landcolor = "white", 
      showframe = FALSE,
      subunitcolor = outline_color 
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white",
    margin = list(t = 120), 
    legend = list(title = "Legend Title") 
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "mentalhealth_missing.html")
#cat("<a href='mentalhealth_missing.html' download>Download Interactive Map (HTML)</a>")
```
```{r}
#calculate ratio of average mental health illness by missing persons
averaged_data$Mental_Missing_Ratio <- averaged_data$Average_AMIYR * averaged_data$Avg_Proportion_Missing_Pop

#filter out Alaska
averaged_data_filtered <- averaged_data %>%
  filter(c(State != "Alaska"), (State != "District of Columbia"))

color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Average Mental Health Illness by Missing Persons Ratio (Excluding Alaska)"

#create choropleth for ratio
map_plot <- plot_ly(data = averaged_data_filtered, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Mental_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average AMIYR: ", Average_AMIYR), colors = color_palette) %>%
  colorbar(title = "Ratio") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE, 
      landcolor = "white", 
      showframe = FALSE, 
      subunitcolor = outline_color 
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "mentalhealth_ratio.html")
#cat("<a href='mentalhealth_ratio.html' download>Download Interactive Map (HTML)</a>")
```
```{r}
color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Average Mental Health Illness by Missing Persons Ratio"

#create choropleth for ratio excluding Alaska
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Mental_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average AMIYR: ", Average_AMIYR), colors = color_palette) %>%
  colorbar(title = "Ratio") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE, 
      landcolor = "white", 
      showframe = FALSE, 
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title") 
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "mentalhealth_ratio_alaska.html")
#cat("<a href='mentalhealth_ratio_alaska.html' download>Download Interactive Map (HTML)</a>")
```


```{r}
title_text <- "Illicit Drug Use vs Proportion of Missing Persons in State Population"
hover_text <- paste("State: ", averaged_data$State, "<br>ILLMON: ", averaged_data$Average_ILLMON, "<br>Proportion Missing Population: ", averaged_data$Avg_Proportion_Missing_Pop)

#create scatter plot for illicit drug use vs proportion of missing persons
 illicit_drug_scatter <- plot_ly(
  data = averaged_data,
  x = ~Average_ILLMON,
  y = ~Avg_Proportion_Missing_Pop,
  text = hover_text,
  mode = "markers",
  marker = list(size = 12, color = "#720026", opacity = 0.5)
) %>%
  layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    xaxis = list(title = "Average Illicit Drug Use (ILLOM) Score", titlefont = list(size = 12)),
    yaxis = list(
      title = "Missing Persons per 100k",
      titlefont = list(size = 12) 
    ),
    showlegend = FALSE,
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title")
  )

illicit_drug_scatter

#uncomment the following lines to download plot as html
#saveWidget(illicit_drug_scatter, file = "drug_scatter_alaska.html")
#cat("<a href='drug_scatter_alaska.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
title_text <- "Mental Illness vs Proportion of Missing Persons in State Population"
hover_text <- paste("State: ", averaged_data$State, "<br>AMIYR: ", averaged_data$Average_AMIYR, "<br>Proportion Missing Population: ", averaged_data$Avg_Proportion_Missing_Pop)

#create scatter plot for mental illness vs proportion of missing persons
mental_scatter <- plot_ly(
  data = averaged_data,
  x = ~Average_AMIYR,
  y = ~Avg_Proportion_Missing_Pop,
  text = hover_text,
  mode = "markers",
  marker = list(size = 12, color = "#720026", opacity = 0.5)
) %>%
layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black") 
    ),
    xaxis = list(title = "Average Any Mental Illness (AMI) Score (18 or older)", titlefont = list(size = 12)),
    yaxis = list(
      title = "Missing Persons per 100k",
      titlefont = list(size = 12) 
    ),
    showlegend = FALSE,
    paper_bgcolor = "white", 
    margin = list(t = 120), 
    legend = list(title = "Legend Title")
  )

mental_scatter

#uncomment the following lines to download plot as html
#saveWidget(mental_scatter, file = "mentalhealth_scatter_alaska.html")
#cat("<a href='mentalhealth_scatter_alaska.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
title_text <- "Mental Illness vs Proportion of Missing Persons in State (Excluding Alaska)"
hover_text <- paste("State: ", averaged_data_filtered$State, "<br>AMIYR: ", averaged_data_filtered$Average_AMIYR, "<br>Proportion Missing Population: ", averaged_data_filtered$Avg_Proportion_Missing_Pop)

#create scatter plot for mental illness vs proportion of missing persons excluding Alaska
mental_scatter2 <- plot_ly(
  data = averaged_data_filtered,
  x = ~Average_AMIYR,
  y = ~Avg_Proportion_Missing_Pop,
  text = hover_text,
  mode = "markers",
  marker = list(size = 12, color = "#720026", opacity = 0.5)
) %>%
layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    xaxis = list(title = "Average Any Mental Illness (AMI) Score (18 or older)", titlefont = list(size = 12)),
    yaxis = list(
      title = "Missing Persons per 100k",
      titlefont = list(size = 12)
    ),
    showlegend = FALSE,
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

mental_scatter2

#uncomment the following lines to download plot as html
#saveWidget(mental_scatter2, file = "mentalhealth_scatter.html")
#cat("<a href='mentalhealth_scatter.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
title_text <- "Illicit Drug Use vs Proportion of Missing Persons (Excluding Alaska)"
hover_text <- paste("State: ", averaged_data_filtered$State, "<br>ILLMON: ", averaged_data_filtered$Average_ILLMON, "<br>Proportion Missing Population: ", averaged_data_filtered$Avg_Proportion_Missing_Pop)

#create scatter plot for illicit drug use vs proportion of missing persons (excluding Alaska)
 illicit_drug_scatter2 <- plot_ly(
  data = averaged_data_filtered,
  x = ~Average_ILLMON,
  y = ~Avg_Proportion_Missing_Pop,
  text = hover_text,
  mode = "markers",
  marker = list(size = 12, color = "#720026", opacity = 0.5)
) %>%
  layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    xaxis = list(title = "Average Illicit Drug Use (ILLOM) Score", titlefont = list(size = 12)),
    yaxis = list(
      title = "Missing Persons per 100k",
      titlefont = list(size = 12)
    ),
    showlegend = FALSE,
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

illicit_drug_scatter2

#uncomment the following lines to download plot as html
#saveWidget(illicit_drug_scatter2, file = "drug_scatter.html")
#cat("<a href='drug_scatter.html' download>Download Interactive Map (HTML)</a>")
```


```{r}
title_text <- "Average Violent Crime Rates Over Time (Reported offenses per 100,000 population)"

#filter the data to include only years between 1960 and 2018 (all data capped at 2018)
state_crime_new_dates <- state_crime_final %>%
  filter(Year >= 1960 & Year <= 2018)

#calculate average violent crime rates over years
averaged_crimes_year <- state_crime_new_dates %>%
  group_by(Year) %>%
  summarize(Average_Violent_Crime = mean(Data.Rates.Violent.All, na.rm = TRUE))

#filter the data to include only years 2016-2018
state_crime_less_dates <- state_crime_final %>%
  filter(Year >= 2016 & Year <= 2018)

#calculate average violent crime rates by state
averaged_crimes_state <- state_crime_less_dates %>%
  group_by(State) %>%
  summarize(Average_Violent_Crime = mean(Data.Rates.Violent.All, na.rm = TRUE))

#create line plot for average violent crime rates over time
crime_plot <- plot_ly(
  data = averaged_crimes_state,
  x = ~Year,
  y = ~Average_Violent_Crime,
  type = 'scatter',
  mode = 'lines+markers',
  marker = list(size = 6, color = '#720026'),
  line = list(color = '#720026')
) %>%
layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    xaxis = list(title = "Year", titlefont = list(size = 12)),
    yaxis = list(
      title = "Average Violent Crime Rates",
      titlefont = list(size = 12)
    ),
    showlegend = FALSE,
    paper_bgcolor = "white", 
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

crime_plot

#uncomment the following lines to download plot as html
#saveWidget(crime_plot, file = "crime.html")
#cat("<a href='crime.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
#merge averaged_data dataframe with averaged_crimes_state dataframe based on state
averaged_data <- left_join(averaged_data, averaged_crimes_state, by = "State")
```

```{r}
title_text <- "State-wise Distribution of Average Violent Crime (per 100,000 Population)"

#create choropleth to see distribution of average violent crime per 100,000 population by state
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Average_Violent_Crime, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE, 
      showland = TRUE,
      landcolor = "white", 
      showframe = FALSE,
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "dist_crimes_100k.html")
#cat("<a href='dist_crimes_100k.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
averaged_data$Crime_Missing_Ratio <- averaged_data$Average_Violent_Crime * averaged_data$Avg_Proportion_Missing_Pop

averaged_data_filtered <- averaged_data %>%
  filter(c(State != "Alaska"), (State != "District of Columbia"))

color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Violent Crime by Missing Persons Ratio (Excluding Alaska)"

#create choropleth map
map_plot <- plot_ly(data = averaged_data_filtered, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Crime_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average Violent Crime Rate: ", Average_Violent_Crime), colors = color_palette) %>%
  colorbar(title = "Ratio") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE,
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "crime_ratio.html")
#cat("<a href='crime_ratio.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
#calculate ratio of violent crime to missing persons
averaged_data$Crime_Missing_Ratio <- averaged_data$Average_Violent_Crime * averaged_data$Avg_Proportion_Missing_Pop

averaged_data_filtered <- averaged_data %>%
  filter(c(State != "Alaska"), (State != "District of Columbia"))

color_palette <- colorRampPalette(c("white", "#720026"))(100)

title_text <- "Violent Crime by Missing Persons Ratio"

#create a choropleth map
map_plot <- plot_ly(data = averaged_data, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Crime_Missing_Ratio, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count, "<br>Average Violent Crime Rate: ", Average_Violent_Crime), colors = color_palette) %>%
  colorbar(title = "Ratio") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE, 
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white", 
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "crime_ratio_alaska.html")
#cat("<a href='crime_ratio_alaska.html' download>Download Interactive Map (HTML)</a>")
```



```{r}
title_text <- "State-wise Distribution of Average Violent Crime per 100,000 population (Excluding Alaska)"

#create choropleth map
map_plot <- plot_ly(data = averaged_data_filtered, type = 'choropleth', locations = ~Abbreviation, locationmode = "USA-states", z = ~Average_Violent_Crime, text = ~paste("State: ", State, "<br>Count of Missing People: ", Count), colors = color_palette) %>%
  colorbar(title = "") %>%
  layout(
    geo = list(
      scope = "usa",
      showcoastlines = TRUE,
      showland = TRUE,
      landcolor = "white",
      showframe = FALSE,
      subunitcolor = outline_color
    ),
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

map_plot

#uncomment the following lines to download plot as html
#saveWidget(map_plot, file = "dist_crime_100k.html")
#cat("<a href='dist_crime_100k.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
title_text <- "Violent Crime Rates vs Proportion of Missing Persons in State Population"
hover_text <- paste("State: ", averaged_data$State, "<br>Average Violent Crime Rate: ", averaged_data$Average_Violent_Crime, "<br>Proportion Missing Population: ", averaged_data$Avg_Proportion_Missing_Pop)

#create scatter plot
crime_scatter <- plot_ly(
  data = averaged_data,
  x = ~Average_Violent_Crime,
  y = ~Avg_Proportion_Missing_Pop,
  text = hover_text,
  mode = "markers",
  marker = list(size = 12, color = "#720026", opacity = 0.5)
) %>%
layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    xaxis = list(title = "Average Violent Crime Rate", titlefont = list(size = 12)),
    yaxis = list(
      title = "Missing Persons per 100k",
      titlefont = list(size = 12)
    ),
    showlegend = FALSE,
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

crime_scatter

#uncomment the following lines to download plot as html
#saveWidget(crime_scatter, file = "crime_prop_alaska.html")
#cat("<a href='crime_prop_alaska.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
title_text <- "Violent Crime Rates vs Proportion of Missing Persons in State Population (Excluding Alaska)"
hover_text <- paste("State: ", averaged_data_filtered$State, "<br>Average Violent Crime Rate: ", averaged_data_filtered$Average_Violent_Crime, "<br>Proportion Missing Population: ", averaged_data_filtered$Avg_Proportion_Missing_Pop)

#create scatter plot
crime_scatter <- plot_ly(
  data = averaged_data_filtered,
  x = ~Average_Violent_Crime,
  y = ~Avg_Proportion_Missing_Pop,
  text = hover_text,
  mode = "markers",
  marker = list(size = 12, color = "#720026", opacity = 0.5)
) %>%
layout(
    title = list(
      text = title_text,
      font = list(size = 15, color = "black")
    ),
    xaxis = list(title = "Average Violent Crime Rate", titlefont = list(size = 12)),
    yaxis = list(
      title = "Missing Persons per 100k",
      titlefont = list(size = 12)
    ),
    showlegend = FALSE,
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Legend Title")
  )

crime_scatter

#uncomment the following lines to download plot as html
#saveWidget(crime_scatter, file = "crime_prop.html")
#cat("<a href='crime_prop.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
missing_sex <- table(missing_final$Biological.Sex)
colors <- c("#720026", "#CE4257")

#create donut chart
donut_chart <- plot_ly(
  labels = names(missing_sex),
  values = missing_sex,
  type = "pie",
  hole = 0.6,
  marker = list(colors = colors)
) %>%
layout(
  title = list(
    text = "Distribution of Missing Persons by Gender (Sex)",
    font = list(size = 15, color = "black")
  ),
  paper_bgcolor = "white",
  margin = list(t = 120),
  legend = list(title = "Legend Title")
)

donut_chart

#uncomment the following lines to download plot as html
#saveWidget(donut_chart, file = "sex_pie.html")
#cat("<a href='sex_pie.html' download>Download Interactive Map (HTML)</a>")
```

```{r}
#create summary table of missing persons count by state and sex
missing_state_sex <- missing_final %>%
  group_by(State, Biological.Sex) %>%
  summarise(Count = n()) %>%
  ungroup()

#create stacked bar chart
stacked_bar_chart <- plot_ly(
  data = missing_state_sex,
  x = ~State,
  y = ~Count,
  type = 'bar',
  color = ~Biological.Sex,
  colors = c("#CE4257", "#720026"),
  text = ~paste("State: ", State, "<br>Sex: ", Biological.Sex, "<br>Count: ", Count),
  hoverinfo = "text"
) %>%
  layout(
    title = list(
      text = "Distribution of Missing Persons by State and Sex",
      font = list(size = 15, color = "black")
    ),
    barmode = 'stack',
    xaxis = list(title = "State", titlefont = list(size = 12)),
    yaxis = list(title = "Total Count of Missing People", titlefont = list(size = 12)),
    paper_bgcolor = "white",
    margin = list(t = 120),
    legend = list(title = "Sex")
  )

stacked_bar_chart

#uncomment the following lines to download plot as html
#saveWidget(stacked_bar_chart, file = "sex_stacked_bar.html")
#cat("<a href='sex_stacked_bar.html' download>Download Interactive Map (HTML)</a>")
```

